#!groovy

// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

node {
  currentBuild.result = "SUCCESS"

  // https://www.quernus.co.uk/2016/10/03/wipe-workspace-jenkins-2.0-deletedir/
  deleteDir() // wipe the workspace

  try {
    stage('Checkout') {
      checkout scm
    }

    stage('Test 2.2') {
      sh 'tox -e ansible22'
    }

    stage('Test 2.3') {
      sh 'tox -e ansible23'
    }
  }

  catch (err) {
    currentBuild.result = "FAILURE"
    throw err
  }
}
