Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.hostname = "network-interfaces-ubuntu"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
#      ansible.galaxy_role_file = '../molecule/default/requirements.yml'
    end
    # NOTE: https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    #       This will remove the ubuntu-xenial-16.04-cloudimg-console.log file
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end
end
