---
- name: network all interfaces changed
  become: {{ become }}
  service:
    name: "{{ network_service }}"
    state: restarted
  when: network_allow_service_restart
  register: network_service_restart_result

- name: network restart interface service
# schema: network_configuration_result.results
#   = [ { "item": [ <device>, [<config>, ...] ], ... }, ... ]
  become: {{ become }}
  service:
    name: "{{ network_service }}"
    state: restarted
    arguments: "INTERFACE={{ item.item.0 }}"
  when: >
    (network_service_restart_result is undefined or not network_service_restart_result.changed)
    and ('service' == network_restart_method)
    and item.changed
    and item.item.1.0.auto | default(true)
  with_items: "{{network_configuration_result.results | default([])}}"

- name: network restart interface command
  become: {{ become }}
  shell: >
    {{ network_interface_restart_commands[ network_restart_method ] }}
  vars:
    device: "{{ item.item.0 }}"
    configs: "{{ item.item.1 }}"
  when: >
    (network_service_restart_result is undefined or not network_service_restart_result.changed)
    and (network_restart_method in network_interface_restart_commands)
    and item.changed
    and item.item.1.0.auto | default(true)
  with_items: "{{network_configuration_result.results | default([])}}"
