---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"

  tasks:
    - name: Create security group
      os_security_group:
        cloud: molecule
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
      register: security_group

    - name: Create security group rules
      os_security_group_rule:
        cloud: molecule
        security_group: "{{ security_group_name }}"
        protocol: "{{ item.proto | default(omit) }}"
        port_range_min: "{{ item.port | default(omit) }}"
        port_range_max: "{{ item.port | default(omit) }}"
        remote_ip_prefix: "{{ item.cidr | default(omit) }}"
        remote_group: "{{ item.group | default(omit) }}"
        ethertype: "{{ item.ethertype | default(omit) }}"
      with_items: "{{ security_group_rules }}"

    - name: Test for presence of local keypair
      stat:
        path: "{{ keypair_path }}"
      register: keypair_local

    - name: Delete remote keypair
      os_keypair:
        cloud: molecule
        name: "{{ keypair_name }}"
        state: absent
      when: not keypair_local.stat.exists

    - name: Create keypair
      os_keypair:
        cloud: molecule
        name: "{{ keypair_name }}"
      register: keypair

    - name: Persist the keypair
      copy:
        dest: "{{ keypair_path }}"
        content: "{{ keypair.key.private_key }}"
        mode: 0600
      when: keypair.changed

    - name: Create networks
      os_network:
        cloud: molecule
        name: "{{ item.name }}"
        provider_network_type: "{{ item.network_type | default(omit) }}"
        shared: "{{ item.shared | default(omit) }}"
        external: "{{ item.external | default(omit) }}"
        provider_segmentation_id: "{{ item.segmentation_id | default(omit)}}"
        provider_physical_network: "{{ item.provider_physical_network | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
      with_items: "{{ neutron.networks }}"
      run_once: true

    - name: Gather facts about network for use with instance creation
      os_networks_facts:
        cloud: molecule
        name: "{{ neutron.networks[0].name }}"

    - name: Create subnets
      os_subnet:
        cloud: molecule
        name: "{{ item.name }}"
        network_name: "{{ item.network_name }}"
        cidr: "{{ item.cidr }}"
        enable_dhcp: "{{ item.enable_dhcp }}"
        gateway_ip: "{{ item.gateway_ip | default(omit) }}"
        ip_version: "{{ item.ip_version | default(omit) }}"
        ipv6_ra_mode: "{{ item.ipv6_ra_mode | default(omit) }}"
        ipv6_address_mode: "{{ item.ipv6_ra_mode | default(omit) }}"
        dns_nameservers: "{{ item.dns_nameservers | default(omit) }}"
        allocation_pool_start: "{{ item.pool_start | default(omit) }}"
        allocation_pool_end: "{{ item.pool_end | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
      with_items: "{{ neutron.subnets }}"
      run_once: true

    - name: Create routers
      os_router:
        cloud: molecule
        name: "{{ item.name }}"
        network: "{{ item.network_name }}"
        interfaces: "{{ item.interfaces }}"
        external_fixed_ips: "{{ item.external_fixed_ips | default(omit) }}"
      with_items: "{{ neutron.routers }}"
      run_once: true

    - name: Create molecule instance(s)
      os_server:
        cloud: molecule
        name: "molecule{{ lookup('env', 'TRAVIS_JOB_ID')|default('') }}"
        image: "{{ nova.image }}"
        flavor: "{{ nova.flavor }}"
        security_groups:
          - "{{ security_group_name }}"
        key_name: "{{ keypair_name }}"
        nics:
          - net-id: "{{ openstack_networks[0]['id'] }}"
        config_drive: yes
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: os_jobs
      until: os_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.openstack.name }}",
          'address': "{{ item.openstack.accessIPv4 }}",
          'user': "{{ ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ keypair_path }}"}
      with_items: "{{ os_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
      with_items: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
