---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: molecule$TRAVIS_JOB_ID
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
